version: "3"

services:
  flask:
    build: .
    container_name: flask
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:6.2-alpine"
    container_name: redis

  nginx:
    image: "nginx:alpine"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "443:443"
      - "80:80"
    links:
      - "flask:flask"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"