version: "3"

services:
  flask:
    build: .
    container_name: flask
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:6.2-alpine"
    container_name: redis

  nginx-proxy:
    image: "nginx"
    volumes:
      - /root/nginx_conf/:/etc/nginx/conf.d
      - /root/nginx_cert:/etc/nginx/nginx_cert
    ports:
      - "443:443"