version: "3"

services:
  flask:
    build: .
    container_name: flask
    ports:
      - "9378"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:6.2-alpine"
    container_name: redis
    ports:
      - "6379"